changelog:
  categories:
    - title: Features
      labels: [feat]
    - title: Fixes
      labels: [fix]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
